### ISSUE TITLE
Feature: file.copy should support downloads

### ISSUE THREAD

**Issue by mt-inside** [comtrya/comtrya#120]
It's pretty common to want to download software (or maybe config) from http, even ftp.
`wget` can be run from command.run, but you have to dump it in /tmp etc etc.
It feels nice to model this by supporting http etc URL schemes in file.copy (file:// can be the default in the case of no scheme)

**Comment by rawkode** [comment]
@mt-inside I added a HttpDownload atom recently that would provide the basis for this. I'll work on adding a user facing action for it this week 👍🏻

**Comment by rawkode** [comment]
@mt-inside `file.download` action will be available shortly 👍🏻
