### ISSUE TITLE
Manifests in subfolders should keep the folder name in their identifier

### ISSUE THREAD

**Issue by svallory** [comtrya/comtrya#124]
Right now if I have a manifest in a subfolder e.g. `formulas/1password.yml` the folder is either ignored or stripped away by `manifest_load`. It is confusing because the `depends` will expect only the filename while we are used to specifying the path for an import.

Also, if I have a manifest with the same name in another folder it looks like the second manifest to be loaded silently replaces the first.

**Comment by rawkode** [comment]
Hey @svallory, thank you for taking the time to provide feedback on Comtrya :)

You're 100% right, this behaviour isn't great.

If manifests where resolved using the directory name, would this work better do you think?

Example:

```
- dev/main.yml
- dev/vscode.yml
- os/defaults.yml
```

These would be resolvable on the CLI and dependencies as `dev`, `dev.vscode`, and `os.default`

If you have any suggestions on how naming should work, I would love to take them onboard

**Comment by svallory** [comment]
Yep, that is exactly what I had in mind. If it is not too much work, allowing to specify to the cli `-m dev/*` and `dev.*` in the `depends` property would be nice too

**Comment by rawkode** [comment]
No problem :)

**Comment by rawkode** [comment]
Closed by #134
