### ISSUE TITLE
Swap Koto for Rhai?

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#163]
Putting this in the maybe pile.

Pro of Rhai? Expression only mode and a simpler context model

https://rhai.rs/book/engine/expressions.html

As we'd only be using expressions, the user facing API for variants likely wouldn't be affected.

Rhai also has considerably better documentation.

**Comment by rawkode** [comment]
Request for comments @bketelsen @icepuma

**Comment by icepuma** [comment]
Hmm. Regarding the Plugin - Feature. Should I just drop the `koto` - Runtime?

**Comment by rawkode** [comment]
@icepuma Is that a major problem / work?

**Comment by icepuma** [comment]
Nope, because the feature is not done, it's easy to just drop it.

:+1: for `Rhai`
