### ISSUE TITLE
FR: Properly deal with `apt-key add` deprecation

### ISSUE THREAD

**Issue by Lockszmith-GH** [comtrya/comtrya#172]
## The Background
`apt-key add` is being deprecated.

Quoting the [The Debian WIKI](https://wiki.debian.org/DebianRepository/UseThirdParty):
> ... The key MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add.

Here is a rather good article that explains how to add keys properly:
> https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html

It is also reflected in the more-up-to-date vendor's documentation, like google-cloud-cli ([link](https://cloud.google.com/sdk/docs/install#debianubuntu)):
> If your distribution (Debian 11+ or Ubuntu 21.10+) doesn't support apt-key, run the following command:
> ```
> curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cl
> ```

The above is just to state, that this has '_become a thing_'.

## The request:
Using `apt-key` should be replaced with the process of adding a key to `/usr/share/keyrings` and then referring to it in the '/etc/apt/sources.d/repo-name.list` file.
Maybe even adding an option to mention a GPG fingerprint (or better yet, a URL to a FINGERPRINT) to be downloaded.

## Some examples
An example of grabbing the gpg file and storing it (note: will require sudo)
```
wget -O- <https://example.com/key/repo-key.gpg> | gpg --dearmor | sudo tee /usr/share/keyrings/<myrepository>-archive-keyring.gpg
```
followed by
```
sudo apt-add-repository "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/<myrepository>-archive-keyring.gpg] https://repository.example.com/debian/ $(lsb_release -cs) stable main "
```

**Comment by rawkode** [comment]
I had no idea. Thank you, @Lockszmith-GH - we’ll fix this

**Comment by Lockszmith-GH** [comment]
A [good explanation](https://stackoverflow.com/a/71384057/799379) of the 'why' behind the deprecation - in case someone is interested:

**Comment by rawkode** [comment]
@Lockszmith-GH I think the PR I just opened should resolve this, though I've got some testing to o.

**Comment by Lockszmith-GH** [comment]
I'll be happy to test out.
In the meantime, here is a bash script I wrote for myself to add repositories - I compiled it after cross referencing all the different solutions and came up with this:
https://github.com/Lockszmith/dotfiles/blob/main/_home/private_dot_local/bin/executable_sz-add-my-apt-repos

Hope this helps you - at least with scaffolding tests
