### ISSUE TITLE
Need some examples

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#190]
I'm so excited exploring this project, I want to move to comtrya, are there examples that I can refer?

**Comment by rawkode** [comment]
The best place for now is probably my dotfiles 

https://github.com/rawkode/rawkode

there’s a dotfiles directory. 

We’re working on a more sophisticated test suite which will contain examples of every action too, but that’s a work in progress.

**Comment by shawn111** [comment]
https://github.com/topics/comtrya can find some examples from github.

**Comment by martintc** [comment]
I am going to close this issue since we have an examples direction with some samples. If there are missing examples, please feel free to open an issue requesting specific examples.
