### ISSUE TITLE
Allow specify configuration file path

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#195]
Hi, can we specify the configuration file path?

I have some variables that I don't want to commit to the public repo, so I place it in a private repo, I want to specify the `Comtrya.yaml` like `-c ~/xxx/Comtrya.yaml`.

**Comment by rawkode** [comment]
Yep, we should support this.

**Comment by martintc** [comment]
To make sure I understand the requirements. Instead of putting variables in your comtrya manifests, you want to be able to point to a file for Comtrya to draw those from. So, something like

`comtrya -d ./Comtrya.yaml apply -c /path_to_file/with_variables`

**Comment by martintc** [comment]
Looks like @davenport1 took care of this. So I will close the issue.
