### ISSUE TITLE
Rework Context Enum

### ISSUE THREAD

**Issue by icepuma** [comtrya/comtrya#211]
The `Context` enum needs some rework:

```rust
pub enum Context {
    KeyValueContext(String, String), // <-- This should be (String, Value)
    ListContext(String, Vec<String>), // <-- This should be (String, Vec<Value>)
}
```

Change depending code accordingly.

This helps comtrya to be more flexible e.g. when loading variables from `.toml` files.

**Comment by icepuma** [comment]
We're currently using the `serde_yaml::Value` - enum for the contexts. I have no problem using it, but in the case of the toml variables include I have to map `serde_toml::Value` to `serde_yaml::Value`. 

Should we introduce our own `Value` - enum without being tied to a framework?

What are your opinions? @comtrya/maintainers

**Comment by martintc** [comment]
I like the idea of introducing our own Value as an abstraction for `serde_toml::Value` and `serde_yaml::Value`. It would improve some on maintainability but also allows us to expand into other formats, for instance if we wanted to integrate json as an option for whatever reason.

**Comment by rawkode** [comment]
I think our own Value enum might be best here 👍🏻
