### ISSUE TITLE
Get rid of `tera`

### ISSUE THREAD

**Issue by icepuma** [comtrya/comtrya#214]
`comtrya` has two engines for evaluation: `tera` and `rhai`. `tera` should be obsolete, as `rhai` supports all necessary use cases. To make it a bit more consistent, we should get rid of `tera`.

**Attention:**
Port the `read_file_contents` function to `rhai`!

**Comment by rawkode** [comment]
@icepuma Can Rhai handle the templating of manifests? I think that's all we use it for atm.

**Comment by icepuma** [comment]
Hmm. I'll have to check.

**Comment by icepuma** [comment]
Meeh. Didn't put in too much thoughts. `tera` is our only option for templating right now. Thanks @rawkode for the hint :D
