### ISSUE TITLE
Bug: Errors are logged on debug level

### ISSUE THREAD

**Issue by bomgar** [comtrya/comtrya#247]
**Description**
Errors are logged on debug 

```
 INFO manifest_run{manifest="install"}: Step: The file ... contents needs to be linked from ... (Not printing initializers and finalizers yet)
DEBUG manifest_run{manifest="install"}: Atom failed to execute: File exists (os error 17)
```

**Steps to reproduce**
Have an existing symlink in the target location

**Expected behaviour**
Error message should not be logged with debug

**Environment**
- OS Linux
- Version: `0.7.4`

**Comment by rawkode** [comment]
Output is definitely something we want to improve. Thanks for raising this.

**Comment by martintc** [comment]
Merged in a PR. I think this particular issue was take care of previously, but I used it as an opportunity to check if in other places we are logging debug when it should be error. If there is any more places or instances where this happens, please open PR. Thank you!
