### ISSUE TITLE
Remote Manifests

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#25]
Manifests shouldn't have to be on the local machine. However, this will require Git installed

**Comment by vielmetti** [comment]
Rust does have a library that wraps Git, at https://github.com/rust-lang/git2-rs - the underlying code is the C library `libgit2`.

**Comment by rawkode** [comment]
Yeah. I’ve been working on a GitOps library based on that for a while. Think this is my time to get it across the line. 

https://GitLab.com/rawkode/gitsync
