### ISSUE TITLE
Bug: Lock file not in repository

### ISSUE THREAD

**Issue by bomgar** [comtrya/comtrya#250]
**Description**
Rust binaries should include a `Cargo.lock` file in the repository.

**Additional information**
I created the [AUR comtrya](https://aur.archlinux.org/packages/comtrya) package. Currently I cannot use `--locked` to make reproducible builds.

**Comment by rawkode** [comment]
@bomgar Added. Hope this helps

**Comment by bomgar** [comment]
Thanks. I will use this with the next comtrya release then.

**Comment by rawkode** [comment]
@bomgar I can either:

1. Add a lockfile to our most recent release
2. Cut an RC release of the next version

Do you have a preference?

**Comment by bomgar** [comment]
I can wait for the next release. I don't think it is that urgent.
