### ISSUE TITLE
Feature: file.remove and directory.remove

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#268]
**Description**
Describe the idea / feature request in your own words.

- removes file or directory
- doesn't error if file/directory doesn't exist

```yml
action: file.remove
target: /some/absolute/path
```

```yml
action: file.remove
target: ~/some/path/in/home
```

```yml
action: file.remove
target: "{{use.home_dir}}/some/path/in/home"
```

```yml
action: directory.remove
target: /some/absolute/path
```

```yml
action: directory.remove
target: ~/some/path/in/home
```

```yml
action: directory.remove
target: "{{use.home_dir}}/some/path/in/home"
```

**Additional information**
Add more context which didn't fit in the fields above.

we should have separate actions for `file.remove` and `directory.remove` because : 

- good future maintenance: it means we don't create navel-gazing-drain-the-ocean-minutea-problems by trying to combine the two.
- maintain the api predictability: because there is already distinct apis for `file` and `directory`

**Comment by bjoroen** [comment]
I would love to work on this. I have a few days off work, so ill try to hack it out.
