### ISSUE TITLE
Feature: allow specifying version of comtrya when installing it.

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#269]
**Description**
Describe the idea / feature request in your own words.

```bash
curl -fsSL https://get.comtrya.dev | COMTRYA_VERSION=x.x.x sh
```

**Additional information**
Add more context which didn't fit in the fields above.

This will give you the freedom to make breaking changes in comtrya while we remain pinned to previous versions.

**Comment by rawkode** [comment]
Hopefully supported by https://github.com/comtrya/get.comtrya.dev/commit/a2a87bbc20714b48692a17973e48f3e5289a35b6

You can test this with:

`curl -fsSL https://comtrya-get.onrender.com | sudo VERSION=v0.7.4 sh`

**Comment by rawkode** [comment]
Now available at https://get.comtrya.dev

**Comment by airtonix** [comment]
:tada
