### ISSUE TITLE
Feature: cli flag to skip cache

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#273]
**Description**
It looks like there's some kind of cache thing going on.

Seems confusing because none of this tool is extensively documented yet.

```powershell

> comtrya apply --no-cache
```

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by icepuma** [comment]
Hmm. We don't have a cache in place oO

**Comment by airtonix** [comment]
Maybe cache isn't the right word, but there's clearly logic in all the actions that determine if it should take action or not.

I see output in the terminal that indicates it decided to not copy files because they haven't changed or something like that.

**Comment by rawkode** [comment]
@airtonix There's no cache, but we perform a `plan` step before we execute our "atoms".

Atoms are individual actions on your machine.

Example:

When you do `file.copy`, that's actually a `touch FILE`, `write contents to file`, and `chmod` of the file.

If the file exists, we don't touch.
If the contents are the same, we don't rewrite them
If the mods are what we expect, we don't reset them

If you have a valid use-case for skipping plan checks, please reopen with further details.
