### ISSUE TITLE
Bug: manifest with action containing a where statement prevents all further actions from running

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#279]
**Description**

`packagemanagers/scoop.yml`
```yaml
---
where: os.name == "windows"

actions:
  - action: command.run
    command: powershell
    args:
      - "irm get.scoop.sh | iex"
```

`shells/starship/install.yml`

```yaml
---
depends:
  - packagemanagers.scoop

actions:
  - action: command.run
    where: os.name == "linux" || os.name == "macos"
    command: curl
    args:
      - -sS https://starship.rs/install.sh | sh

  - action: command.run
    where: os.name == "windows"
    command: scoop
    args:
      - 'install starship'
```

if i am on windows 11 and i run : 

```powershell
>  comtrya -v apply -m shells.starship.install
```

I see: 

```
DEBUG execute:{manifest="packagemanagers.scoop"}: Result of 'where' condition 'os.name == "windows"' -> 'true'
 INFO execute:{manifest="packagemanagers.scoop"}: Completed
 INFO execute:{manifest="shells.starship.install"}:{action=command.run}: nothing to be done to reconcile action
```

If i comment out the first action that is only intended to run on linux: 

```yaml
---
depends:
  - packagemanagers.scoop

actions:
  # - action: command.run
  #   where: os.name == "linux" || os.name == "macos"
  #   command: curl
  #   args:
  #     - -sS https://starship.rs/install.sh | sh

  - action: command.run
    where: os.name == "windows"
    command: scoop
    args:
      - 'install starship'
```

and run this again: 

```powershell
>  comtrya -v apply -m shells.starship.install
```

then I see: 

```powershell
DEBUG execute:{manifest="packagemanagers.scoop"}: Result of 'where' condition 'os.name == "windows"' -> 'true'
 INFO execute:{manifest="packagemanagers.scoop"}: Completed
DEBUG execute:{manifest="shells.starship.install"}:{action=command.run}: Atom failed to execute: program not found
ERROR execute:{manifest="shells.starship.install"}: Failed
```

Am I using `where` correctly? 

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

**Expected behaviour**
What the expected behaviour in your opinion.

**Environment**
- OS
- Version: `comtrya --version`

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by airtonix** [comment]
btw it fails because for some reason `scoop` is not on the path for `comtrya` but in my powershell shell and my cmd.exe shell it is.

**Comment by icepuma** [comment]
I think the problem is located in our `Exec` - atom call [here]( https://github.com/comtrya/comtrya/blob/main/lib/src/actions/command/run.rs#L38-L43)

We don't set any env, which is used [here](https://github.com/comtrya/comtrya/blob/main/lib/src/atoms/command/exec.rs#L94)
