### ISSUE TITLE
Bug: Tera Function: read_file_contents strips out or doesn't interpret newlines properly.

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#280]
**Description**

- this manifest: https://github.com/airtonix/dotfiles/blob/master/devtools/git/git.yml
- copying and templating these files: 
  - https://github.com/airtonix/dotfiles/blob/master/devtools/git/files/gitconfig
  - https://github.com/airtonix/dotfiles/blob/master/devtools/git/files/id.gitconfig
  - https://github.com/airtonix/dotfiles/blob/master/devtools/git/files/main.gitconfig
  - https://github.com/airtonix/dotfiles/blob/master/devtools/git/files/aliases.gitconfig

ends up creating this `~/.gitconfig`: 

```ini
[user]	name = Zeno Jiricek	email = airtonix@users.noreply.github.com
[core]	editor = code --wait[pull]	rebase = false[init]	defaultBranch = master[rerere]	enabled = true
[alias]	up = push origin HEAD	sync = "!f() { DEFAULT_BRANCH=$(git config --get core.defaultBranch || echo master); [ \"$(git branch --show-current)\" != \"${DEFAULT_BRANCH}\" ] && git fetch origin "${DEFAULT_BRANCH}:${DEFAULT_BRANCH}" || git pull; }; f"	fix = "!git stash save && git sync && echo fix | git start"	feature = "!git stash save && git sync && echo feature | git start"	feat = "!git stash save && git sync && echo feat | git start"	docs = "!git stash save && git sync && echo docs | git start"	ci = "!git stash save && git sync && echo ci | git start"	chore = "!git stash save && git sync && echo chore | git start"	start = "!read BRANCH && git checkout -b $BRANCH/$1 $(git config --get core.defaultBranch || echo master); git stash pop"	alias = "! git config --get-regexp ^alias\\. | sed -e 's/^alias\\.\\([^ ]*\\)/\\x1B[33m\\1\\x1B[0m =/'"	pivot = "!f() { WORKTREE_ROOT=$(git config --get core.worktreeRoot || {exit 1}); mkdir -p $WORKTREE_ROOT; git worktree add $WORKTREE_ROOT/$1 $2; code $WORKTREE_ROOT/$1;}; f"

```

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

**Expected behaviour**
What the expected behaviour in your opinion.

- that `.gitconfig` ends up being a concatenation of the intput files.

**Environment**
- OS: Windows 11, Powershell 7
- Version: `0.8.0`

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by airtonix** [comment]
I suspect the issue is the use of `flatten` here on all lines when you probably only want to deal with the last line? 

https://github.com/comtrya/comtrya/blob/main/lib/src/tera_functions/mod.rs#L15

**Comment by rawkode** [comment]
This is a bug here:

https://github.com/comtrya/comtrya/blob/79c1214d3ffa20ad621f79e415d9fe87cbbce155/lib/src/tera_functions/mod.rs#L15

We’ll get this fixed.

**Comment by icepuma** [comment]
I'll fix it
