### ISSUE TITLE
Feature: Context command

### ISSUE THREAD

**Issue by icepuma** [comtrya/comtrya#304]
**Description**
We have a new command `comtrya contexts [--show-values]` which shows the given contexts and optionally their values.

This issue is a placeholder for future discussions and it is linked in the output of the command.

**Comment by rawkode** [comment]
Closed by #298

**Comment by rawkode** [comment]
Oops. Just read it properly 😊

**Comment by martintc** [comment]
I am going to go ahead and close this. If there is any new feature that should be added to this or anything to augment it, we should just open a new issue for that request.
