### ISSUE TITLE
Bug: Broken links

### ISSUE THREAD

**Issue by bjoroen** [comtrya/comtrya#329]
Hey, 

I was looking around trying to find an issue I could do so I can contribute to the project. I noticed a few broken links while looking around.

### Broken links
- In the ```CONTRIBUTING.md``` file, there are two links to Discord and one link to a PR template.
- At the bottom of the ```README.md``` page, there is a link named ```tests```, that returns a 404.

**Comment by icepuma** [comment]
The Discord link works, but the `test` link is indeed broken. I will fix it soon.

**Comment by bjoroen** [comment]
You are right. The discord link does work, It was my browser making it look like it didn't.
