### ISSUE TITLE
Bug: Installing comtrya by following instruction in README fails 

### ISSUE THREAD

**Issue by gverger** [comtrya/comtrya#331]
Hello,

I wanted to try comtrya for my development machine, but my first contact with it is not the best. I can't install it easily.

**Description**
If I follow the instructions in the README to install comtrya, it fails silently.

**Steps to reproduce**

Run
```bash
curl -fsSL https://get.comtrya.dev | sh
```

**Expected behaviour**
Comtrya latest executable should be downloaded.
There is a file `comtrya-x86_64-unknown-linux-gnu` which contains "Not found".

**Environment**
- OS: Ubuntu 22.04 WSL
- Version: v0.8.4

**Additional information**

- It seems the binaries are missing for version 0.8.4
- Using `VERSION=v0.8.3 curl -fsSL https://get.comtrya.dev | sh` fails too: it seems the install script can't get the right version

**Comment by martintc** [comment]
I did the last release and may be taking over more of the releasing. I'll get in touch with Rawkode and see if there are some things I need to do for that.

**Comment by airtonix** [comment]
Yeah I already reported that there's no release for 0.84. There's a possible fix for that over in the website repo

**Comment by martintc** [comment]
I am assuming with the latest releases and we have the how the release works figured out, that it is okay to close this issue.
