### ISSUE TITLE
v0.8.4 has no asset

### ISSUE THREAD

**Issue by suzuki-shunsuke** [comtrya/comtrya#333]
https://github.com/comtrya/comtrya/releases/tag/v0.8.4

<img width="453" alt="image" src="https://github.com/comtrya/comtrya/assets/13323303/aef34a22-300a-4d99-9635-2bb72bce83b0">

Some release jobs failed.

https://github.com/comtrya/comtrya/actions/runs/4899697109/jobs/8749849204

```
Executing cargo clippy (JSON output)
Clippy results: 0 ICE, 0 errors, 0 warnings, 0 notes, 0 help
Error: Clippy had exited with the 101 exit code
```

https://github.com/comtrya/comtrya/actions/runs/4899697109/jobs/8749848929

```
Run softprops/action-gh-release@v1
/usr/bin/docker exec  396c9da55bf404706c8055761e47c244c61b3cf004cec4b02bd1bc805fef67de sh -c "cat /etc/*release | grep ^ID"
⬆️ Uploading comtrya-x86_64-unknown-linux-musl...
Error: request to https://uploads.github.com/repos/comtrya/comtrya/releases/87997824/assets?name=comtrya-x86_64-unknown-linux-musl failed, reason: read ECONNRESET
```

**Comment by martintc** [comment]
Will look into it! I did the previous release and may be taking over making the releases. Will get in touch with Rawkode and see if there is anything I missed or special I need to do for that as part of the pipeline.

**Comment by martintc** [comment]
I am assuming with newer releases being made and it looks like we sorted out the issue on the release end, it is okay to close this.

**Comment by suzuki-shunsuke** [comment]
Thank you!
