### ISSUE TITLE
Bug: aarch64-unknown-linux-gnu does not match aarch64 architecture

### ISSUE THREAD

**Issue by thebino** [comtrya/comtrya#337]
**Description**
The binary release for aarch64-linux does not match the aarch64 architecture but the x86_64 architecture.

**Steps to reproduce**
- Download the binary from [the Release page](https://github.com/comtrya/comtrya/releases/tag/v0.8.5)
- check the file type or the checksum and compare

```shell
~ > file comtrya-aarch64-unknown-linux-gnu
comtrya-aarch64-unknown-linux-gnu: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=1841eef2df0ee3817004296c79f6ab917b72ca1b, for GNU/Linux 3.2.0, with debug_info,
not stripped
~ > file comtrya-x86_64-unknown-linux-gnu
comtrya-x86_64-unknown-linux-gnu: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=1841eef2df0ee3817004296c79f6ab917b72ca1b, for GNU/Linux 3.2.0, with debug_info, n
ot stripped
```

```shell
~ > shasum comtrya-aarch64-unknown-linux-gnu
a16377afda3c6e13e5da59310f60e461e09734eb  comtrya-aarch64-unknown-linux-gnu
~ > shasum comtrya-x86_64-unknown-linux-gnu
a16377afda3c6e13e5da59310f60e461e09734eb  comtrya-x86_64-unknown-linux-gnu
```

**Expected behaviour**
What the expected behaviour in your opinion.

**Environment**
- OS
- Version: `0.8.5`

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by martintc** [comment]
Could you verify that v0.8.7 works just fine?

**Comment by thebino** [comment]
With [v0.8.7](https://github.com/comtrya/comtrya/releases/tag/v0.8.7) the issue still exists with all release artifacts:

```
➜ file *
apple-comtrya-aarch64-apple-darwin:         Mach-O 64-bit executable x86_64
apple-comtrya-x86_64-apple-darwin:          Mach-O 64-bit executable x86_64
linux-comtrya-aarch64-unknown-linux-gnu:    ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=af3f11dbb6f6a1b0a5dc96532227976a1ed967c9, for GNU/Linux 3.2.0, with debug_info, not stripped
linux-comtrya-x86_64-unknown-linux-gnu:     ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=af3f11dbb6f6a1b0a5dc96532227976a1ed967c9, for GNU/Linux 3.2.0, with debug_info, not stripped
linux-comtrya-x86_64-unknown-linux-musl:    ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[sha1]=0107ad7cfff7df76d5141ea08270c8fa19957b71, with debug_info, not stripped
windows-comtrya-x86_64-pc-windows-msvc.exe: PE32+ executable (console) x86-64, for MS Windows
```

```
➜ shasum *
c6d4122a61df8d1d0a04ed2afb781965aa195177  apple-comtrya-aarch64-apple-darwin
c6d4122a61df8d1d0a04ed2afb781965aa195177  apple-comtrya-x86_64-apple-darwin
7e0485eb7210b32fd9deb97412fa78209a3a0732  linux-comtrya-aarch64-unknown-linux-gnu
7e0485eb7210b32fd9deb97412fa78209a3a0732  linux-comtrya-x86_64-unknown-linux-gnu
023c89cd1a596bcd01aef77e83ec9d1c9f4a18a7  linux-comtrya-x86_64-unknown-linux-musl
d81ce2dedc6aa237dd58e87de4221eb3128c6e4b  windows-comtrya-x86_64-pc-windows-msvc.exe
```

**Comment by martintc** [comment]
Alright, yes that is definitely still happening. I have a branch I am playing around with the pr github action to see if I can fix it. Looks like we don't force anywhere to instruct cargo to build for the aarch64 architecture when we are trying to do that, so it kicks out an x86_64 image, so it isnt actually cross compiling. 

I have a branch that appears to cross compile it correctly, but having some issues with test failing.

**Comment by thebino** [comment]
In the action we only set the tool chain and the target.
But the underlying architecture where the build is running is still different, so we probably need to use [cross-rs](https://github.com/cross-rs/cross) or something similar

**Comment by thebino** [comment]
@martintc have you checked your artifacts in that PR already?

**Comment by martintc** [comment]
I think I got it, I'll kick off the action again and have you verify, but it looks like we got it on our side. Sorry it took so long. Life got busy and I also needed to learn a lot more about github actions, but it looks like we got a solution.

**Comment by thebino** [comment]
@martintc Looks good to me, but why aren't you using `cross` for all the builds? Looks like other applications always use cross.

**Comment by rawkode** [comment]
We removed Cross in 2021 because it was abandoned. Specifically, we needed this fix:

https://github.com/cross-rs/cross/pull/543

Cross is currently maintained and active again, so maybe it could be used.

**Comment by martintc** [comment]
I am assuming I can close this out?
