### ISSUE TITLE
docs/examples: Tailscale installation on Ubuntu; requires `apt-key add`

### ISSUE THREAD

**Issue by vielmetti** [comtrya/comtrya#35]
Motivation: one of the first things I do when setting up a new node is put it on my [Tailscale](https://tailscale.com) private network. `comtrya` should make this very easy, at the minimum by installing the necessary binaries, and (ideally) by propagating the necessary secrets or documenting the auth steps needed to turn up the network.

The Tailscale docs here https://tailscale.com/download/linux show the steps, which include downloading a signing key and adding a repository; the signing key in particular may require some updates to the Aptitude libraries to interface to `apt-key add`.

**Comment by vielmetti** [comment]
My workaround version of this is a script at https://github.com/vielmetti/vielmetti-shelltools/blob/master/files/bin/setup-tailscale-ubuntu-focal which I install with a `file.copy` command and then run with `sh -x`.  I do need to cut and paste a URL into my browser on my laptop to authenticate.  Much faster and less error-prone that following the instructions by hand.

**Comment by rawkode** [comment]
This is currently available in a PR: #138

**Comment by icepuma** [comment]
This issue is resolved?

**Comment by rawkode** [comment]
Yep, #138 was merged. Thanks
