### ISSUE TITLE
Apple silicon test runners?

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#392]

**Comment by martintc** [comment]
I looked into this when we updated the other runners. When I last checked, they were a paid for feature and still in beta testing. For sure, when they do become available and free to open source repos, we should definitely add them.

**Comment by martintc** [comment]
Looks like they now have free runners for open source

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
