### ISSUE TITLE
Feature: Install individual package files

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#430]
**Description**
Install individual package files. On FreeBSD, they would be `.pkg` . On Debian, they are `.deb`, etc.

**Additional information**
Provide a way to let the user specify the location of the package file(s). If more than one package file needs to be specified, use a list.

**Comment by martintc** [comment]
To get some idea of implementation. Let me run and example by you and get your feedback.

Suppose we are talking a Debian system. We want to insteall a `.deb` file. With comtrya's package provider interface/system, do you see this as a `package.install` that specifies a provider of `dpkg`. So the action in a manifest would look something like this:

```
- action: package.install
  name: some-deb.deb
  provider: dpkg
```

And it will translate into running the command `sudo dpkg -i some-deb.deb`

**Comment by yonas** [comment]
> do you see this as a package.install that specifies a provider of dpkg

That should be optional.

> Or do you see this as adding an option to specify a file and using apt.

Two ways:

1. If they specify a file path, `file` would be assumed as `true` and be optional. If only a file name is provided, it might help differentiate between a package with a `.deb` suffix in rarest of cases were a `.deb` with that exact file name exists, and a package with that name exists in the package repo.

2. `file: true` is required . I like the verbosity `file: true`, but I don't think it makes sense to be required if a full file path is specified in `name`.

**Comment by martintc** [comment]
There is an initial PR. It just covers FreeBSD if you want to test it out and right now for the file property for the package install action to be set to true. I figure this is a good place to start and to give you something to test out.

**Comment by yonas** [comment]
Thanks again @martintc !

**Comment by martintc** [comment]
> Thanks again @martintc !

No problem at all

**Comment by martintc** [comment]
I think this does it at least so far for this. Feel free to re-open if not.
