### ISSUE TITLE
Feature: add option to ignore user/group already exists + user already a member of group

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#431]
**Description**
When running `user.add` and `user.group`, add a boolean option to treat user already exist and user already a group member as not a failure.

**Additional information**
It would be very useful to simply make sure that the user account exists with the specified details, and not fail if the user already exists. Likewise for creating groups and adding users to groups.

If the user already exists, but any of the attributes are different, Comtrya should make the changes.

**Comment by rawkode** [comment]
What you describe is how it should actually work, no extra Boolean required. 

Comtrya actions have plan phases to determine if it needs to run, but existing user checks are missing for the user providers.

**Comment by yonas** [comment]
See PR #453
