### ISSUE TITLE
Bug: Missing regression tests for PR #434

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#435]
Tests should have caught https://github.com/comtrya/comtrya/pull/434 over 2 years ago.

On a side note, if comtrya has an excellent test suite, a lot more devs may see this as a viable alternative to Ansible. You could then provide professional support, etc. To further help make this project even more incredible, all PRs should be accepted with regression tests.

**Comment by rawkode** [comment]
I completely agree. To be quite honest, I stopped using Comtrya. I don't like the YAML interface and opted for Nix instead. 

Of course, Nix has many other challenges and I think Comtrya and Nix could eventually complement each other; but the YAML interface would need to go.

CUE recently provided libcue which allows interopt with Rust and there's even a cue-rs in the works. I'm really tempted to reboot this project with CUE support (YAML would still work).

**Comment by martintc** [comment]
I agree, our test suite is lacking some things for sure.

**Comment by yonas** [comment]
> I'm really tempted to reboot this project with CUE support (YAML would still work).

I like [RCL](https://rcl-lang.org) and [KCL](https://kcl-lang.io).

**Comment by martintc** [comment]
Thanks for those suggestions. I'm not a huge fan of YAML or TOML. So having another or some other alternatives would be nice. I'll take a look at those two at some point and see what I can do to integrate them.
