### ISSUE TITLE
insert developer to continue

### ISSUE THREAD

**Issue by icepuma** [comtrya/comtrya#436]
Hey folks,

we're currently focusing on other things, like building the [Rawkode Academy](https://github.com/RawkodeAcademy/RawkodeAcademy), hence the project doesn't get the love it deserves.

If you or one you know wants to keep comtrya active, please hop on the [Rawkode Academy Discord](https://rawkode.chat/) and we figure out the details :)

Comtrya from @rawkode, @martintc and @icepuma

**Comment by martintc** [comment]
As mentioned on the discord. I have dumped a side project that was taking considerable time. So I should be able to focus on comtrya.
