### ISSUE TITLE
Feature: use run0 on systems v256+ systems

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#451]
Instead of sudo, hook into systemd when available

**Comment by martintc** [comment]
Mostly a note to myself or whoever is interested implementing this.

https://www.freedesktop.org/software/systemd/man/devel/run0.html

**Comment by martintc** [comment]
This PR is a good start and allows for utilization of run0, so Ill close this. Feel free to reopen with feedback or open a new issue for suggest expansion of the feature!
