### ISSUE TITLE
Bug: File commands seem to expect the files in "files" subfolder but this is not documented

### ISSUE THREAD

**Issue by DominicD** [comtrya/comtrya#474]
**Description**
Thank you for this nice tool I am just starting to use it and get to know how to use it.
It seems that the file commands or at least the file.link with walk_dir: true expect the files to be in a "files" folder.
As seen in code https://github.com/comtrya/comtrya/blob/73b462d7040572f60b35912327816a6115258dcf/lib/src/actions/file/mod.rs#L19 and examples https://github.com/comtrya/comtrya/blob/main/examples/file/walk.yaml

**Example manifest**
https://github.com/comtrya/comtrya/blob/main/examples/file/walk.yaml

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

**Expected behaviour**
I was very suprised by this especially because it is not mentioned in the documentation.
In my opinion there should be no need for this implicit need for a "files" folder or at least some documentation.

**Environment**
- WSL 2 Ubuntu 24.04
- Version: [`comtrya --version`](https://github.com/comtrya/comtrya/blob/main/examples/file/walk.yaml)

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by rawkode** [comment]
Hi. Sadly this is a constraint and one we should document better. 

It's because we allow templating of Comtrya manifests, which requires us to isolate non manifest files. 

I've always wanted to remove this restriction, perhaps it's time to work it out. 

I'm going to close this in favour of #96

I'll think of a way to make this work nicely

**Comment by DominicD** [comment]
> Hi. Sadly this is a constraint and one we should document better.
> 
> It's because we allow templating of Comtrya manifests, which requires us to isolate non manifest files.
> 
> I've always wanted to remove this restriction, perhaps it's time to work it out.
> 
> I'm going to close this in favour of #96
> 
> I'll think of a way to make this work nicely

Ah sorry I did not see that issue. Thanks for the clarification.

I still think it would make sense to at least mention it in the docs? 
If you agree I could try to do a PR?

**Comment by rawkode** [comment]
Definitely agree! Would love to see it. Thank you.

**Comment by martintc** [comment]
> > Hi. Sadly this is a constraint and one we should document better.
> > It's because we allow templating of Comtrya manifests, which requires us to isolate non manifest files.
> > I've always wanted to remove this restriction, perhaps it's time to work it out.
> > I'm going to close this in favour of #96
> > I'll think of a way to make this work nicely
> 
> Ah sorry I did not see that issue. Thanks for the clarification.
> 
> I still think it would make sense to at least mention it in the docs? If you agree I could try to do a PR?

As @rawkode said, would love to see it. If you end up not being able to get around to documenting it, let me know I'll make a note of it somewhere and Ill get to it when I can. Its a whole I noticed a couple weeks ago and it just fell through the cracks for me as I was working on getting the new documentation site up.
