### ISSUE TITLE
Bug: getting "yay not available"

### ISSUE THREAD

**Issue by JustinBacher** [comtrya/comtrya#485]
**Description**
Receiving "yay not available" when running `comtrya apply` when yay is not installed

**Example manifest**
```toml
[[actions]]
action = "package.install"
name = "neofetch"
```

**Steps to reproduce**
```
 WARN execute:{manifest=""}:{action=package.install}:package.install{provider="Yay"}: yay not available
 INFO execute:{manifest=""}:{action=package.install}: Action failed to get plan: No such file or directory (os error 2)
ERROR execute:{manifest=""}: Failed
```

**Expected behaviour**
yay be installed automatically then the packages

**Environment**
- OS: arch
- Version: comtrya 0.9.0

**Additional information**
I am working on a PR for including [paru](https://github.com/Morganamilo/paru) in the list of available providers and I found this when I was trying to test and make sure mine worked when paru wasn't installed and when that errored out I tried it with base being yay and got the same error.

I will look into why this isn't working and if I figure it out would it be ok including that into the same PR or should I make them separate PR's? One to first fix yay not getting installed and the second to add paru?

**Comment by martintc** [comment]
The issue here is that the bootstrap method isn't running, which needs to be investigated. Comtrya should be able to bootstrap the package manager if it is not present by installing and setting it up for you. The only two package managers I know off the top of my head the should run a bootstrap is yay for Arch and Arch based systems and brew for macOS.

**Comment by JustinBacher** [comment]
I was looking through the code and I don't see a reason it shouldn't be running the bootstrap. It's being added to the steps unless it's being overwritten somewhere. I don't know how to DAP a package it's new to me. I was thinking of putting in PR's not only for paru but also choco and scoop for windows too so it'd be nice to figure this out.

**Comment by martintc** [comment]
Does PR #498 allow us to close this issue?

**Comment by martintc** [comment]
I am going to assume it does and close the issue, if not, feel free to open with feedback.
