### ISSUE TITLE
Bug: Downloading older versions with getcomtrya no longer works

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#494]
**Description**

```sh
❯ VERSION=v0.8.6 curl -fsSL https://get.comtrya.dev | sudo sh

x86_64
Downloading package https://github.com/comtrya/comtrya/releases/download/v0.9.0/comtrya-x86_64-unknown-linux-gnu as /tmp/comtrya-x86_64-unknown-linux-gnu
Download complete.

Running with sufficient permissions to attempt to move comtrya to /usr/local/bin
New version of comtrya installed to /usr/local/bin
comtrya: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by comtrya)
comtrya: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by comtrya)
```

**Example manifest**
Can you provide an example manifest that can demonstrate the problem?

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

**Expected behaviour**
What the expected behaviour in your opinion.

**Environment**
- OS
- Version: `comtrya --version`

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by martintc** [comment]
In the get.comtrya.dev repo, the offender appears to be
```shell
version=$(curl -sI https://github.com/$OWNER/$REPO/releases/${VERSION:=latest} | grep -i "location:" | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')
```

If no version is specified, we use latest, and the response we get back has a location field in the header we parse. But specifying a version, no location header is returned. I don't know if this is a change in how github headers come back, but this is looks like the offending line.

**Comment by martintc** [comment]
Installation script has been updated and deployed. I also need to update the README. Both the script and the README have probably been wrong for awhile. 

If you wouldn't mind, retest with the follow input into your shell and confirm that it works.

```shell
curl -fsSL https://get.comtrya.dev | VERSION=v0.8.8 sh
```

**Comment by airtonix** [comment]
![image](https://github.com/user-attachments/assets/238b3b7f-d380-4017-8b66-22aa8c653101)

sweet!
