### ISSUE TITLE
Feature: File Actions Don't Support Atom chown

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#500]
There's at atom for managing the owner and group of files, but no actions support this.

**Comment by martintc** [comment]
issue #502 is related, its the reason for the draft implementation in #506 requires sudo/doas/run0 when running the comtrya binary for it to work.

**Comment by martintc** [comment]
With #506 complete, just need to implement for the directory set of actions.

**Comment by martintc** [comment]
Should we also support chown for copy the action or does the implementation of the Chown action and optional fields in `file.download` address this?

**Comment by martintc** [comment]
I think that pretty much covers all the ones that could benefit from it. Will close the issue.
