### ISSUE TITLE
Add ability to encrypt/decrypt files

### ISSUE THREAD

**Issue by TomKeur** [comtrya/comtrya#56]
This is a feature request:

Since I'm using a lot of different computers, it would really help me to add the ability to encrypt/decrypt files.
So I can publish them in a public Git repo.

For example I'm using bastion hosts in my `~/.ssh/config` file, but I don't want to be those public (the IP addresses):

```
Host bastion
  HostName 10.10.11.1
  User bastion
  IdentityFile ~/.ssh/bastion
```

In my example I used an internal IP Address, but normally these are public ip addresses. 

I know that [Ansible Vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html) is using AES256 to encrypt/decrypt files, I'm not sure if something like this is working in Rust.

So, maybe add a "Comtrya vault?", with the ability to:

- Encrypt files (with a `comtrya vault` command)
- Decrypt files when running comtrya
- Ability to add a vault_key in the comtrya configuration? For example `~/.comtry/vault_password.txt`, so we don't need to type the password everytime we're running the `comtrya` command. 
- Check the vault file for "world" persmissions, for example only allow it when it's chmod 600? To prevent data leaks :).

**Comment by icepuma** [comment]
Hey. I have some time to spare next week to invest some energy. I would love to contribute this feature. Do you have any thoughts @rawkode or ideas how you want the problem to be solved?

I like the idea @TomKeur described. Any other thoughts on this matter?

Best regards
