### ISSUE TITLE
Output and logging

### ISSUE THREAD

**Issue by kraileth** [comtrya/comtrya#95]
If comtrya is applying the example manifest for command.run this was the output for version 0.6.1:
```
hi
root
  INFO manifest_run{manifest="run"}: Completed
```
As of version 0.6.2 this is the output:
```
  INFO manifest_run{manifest="run"}: RunCommand with privileged false: echo hi
  INFO manifest_run{manifest="run"}: RunCommand with privileged false: whoami 
  INFO manifest_run{manifest="run"}: Completed
```
While it's definitely an improvement to see what was actually done and not just the result, especially in the `whoami` example the result is very much relevant. I think that at least in verbose mode it would make sense to have something like this instead:
```
  INFO manifest_run{manifest="run"}: RunCommand with privileged false: echo hi
  DEBUG Command output was: "hi"
  INFO manifest_run{manifest="run"}: RunCommand with privileged false: whoami
  DEBUG Command output was: "root"
  INFO manifest_run{manifest="run"}: Completed
```
It might also make sense to allow for logging to a file instead of only printing to stdout. Yes, it can be redirected and yes, you can use `tee` to both see it and have it written to a file. However for the log files it would make sense to write just text to them and not the color codes for example. Also prefixing everything with a timestamp would be helpful for taking a look at what actually happened should you figure out later that something went sideways.

This will probably be even more useful once it can be configured in `Comtrya.yaml` instead of having to be specified with each command line.

**Comment by rawkode** [comment]
Command stdout/stderr/exit code are now displayed via trace level logging (-vv)

Closed by #106
